---
layout: cv
title: Natalie Johnson CV
---

<div id="webaddress">
<a href="natalielinford777@gmail.com">natalielinford777@gmail.com</a>

</div>


# Natalie Johnson
Student, TA, and Turor at Brigham Young University – Idaho.



## Education

`2024`
__Brigham Young University – Idaho, Rexburg, ID__

- __B.A.__ Psychology (Health Psychology Emphasis), __Minor:__
Data Science

- __Relevant Classes:__ Research Methods, Experiencing
Research, Intermediate Statistics, Linear Regression



## Occupation

`2022-current`
__Teaching Assistant__, Brigham Young University – Idaho

- Psychology Department
- Supervisor: Rob Wright, Ph.D.

`2023-current`
__Teaching Assistant__, Brigham Young University – Idaho

- Health Services Department
- Supervisor: Geoffrey Loomis, Ph.D.

`2023-current`
__Tutor__, Brigham Young University – Idaho

- Campus Tutoring Center
- Supervisor: Samuel Clay, Ph.D.



## Research interests

Health Psychology, Health Behavior Change, Interventions, Cognition, Obesity, Longevity.



## Manuscript Under Review

- Wright, R.R., Wilson, M., Nienstedt, C., Ewing, C., Rodriguez, A., Anderson, C., __Johnson, N.__, &
Johnson, L. (under review). Quality dating and wellness among a conservative college
student body: A mixed methods approach. Journal of American College Health.



## Professional Research Experience

`2022-current`
__Research Assistant: Health Psychology__

- Faculty Mentor: Rob Wright, Ph.D.
- Contributed to research idea development, literature reviews, qualitative data analysis, and presentations. Contributed to a research publication undergoing peer review. Additionally, I led a team of 15 students in a study aimed at enhancing running performance through mindfulness techniques. My responsibilities included designing and overseeing the study, conducting research analyses, and leading full-scale research using a pre-post-intervention, quasi-experimental research design. The study involved the use of equipment such as heart rate monitors and treadmills.

`2023`
__Student Research Assistant__

- Faculty Mentor: Samuel Clay, Ph.D.
- I collaborated with other students on an exploratory study about different motivations for exercise. We are currently using self-determination theory to understand what motivates college students to exercise and what factors correlate with it, such as age, gender, life satisfaction and subjected health.

`2023`
__Student Research Assistant__

- Faculty Mentor: Scott Martin, Ph.D.
- Assisted a graduate student in a spiritual feeling’s perception dissertation. Developed pilot study, created presentation, delivered it at a research conference.

`2022`
__Student Lead Researcher__

- Faculty Mentor: Rob Wright, Ph.D.
- Led a self-designed project on college students' exercise preferences pre/post COVID-19. Assisted with IRB, data analysis, and conference presentation.



## Professional Research Conference Presentations

`2023`
Wilson, M., Harrison, A., Merrick, S., Wright, S., Layton, M.J., Mouser, S., Johnson, L., __Johnson, N.__,
Price, N., & Wright, R.R. (2023, April). Little Women: Exploring Dating for Young
Women in a Religious Population. Presentation delivered for the annual Rocky Mountain
Psychological Association conference. Albuquerque, NM.



## Media Presentations

- Scroll. Featured “What is the research behind dating?”. The article was published on the “Dating Quality Project” online in the July 10, 2023 edition: Ray, K. (2023).
- BYU-Idaho Radio. Featured “Psychology Students Study the Dating Culture at BYU- Idaho” research conducted with C. Nienstedt, M. Wilson, & __N. Johnson__. The interview was aired during news segment on 1/25/2023. Simmons, C. (2023).



## Teaching

`2022-current`
__Teaching Assistant, Department of Psychology__

- Supervisor: Rob Wright, Ph.D.
- __Courses:__
- PSYCH 435, Health Psychology (10 sections)
- PSYCH 485, Experiencing Research (6 sections)

`2023-current`
__Teaching Assistant, Department of Health Services__

- Supervisor: Geoffrey Loomis, Ph.D.
- __Courses:__
- PUBH 132, Health and Wellness (1 section)
- PUBH 391, Research Methods (3 sections)



## Leadership & Volunteer Experience

`2023-current`
__Data Enhancement & Web Scraping Team Member__

- Worked alongside other members of a campus club to enhance an international real estate company's website.
- Provided insights for website improvements.
- Streamlined real estate data consolidation by capturing property screenshots from multiple websites, optimizing information access on a unified platform.

`2023-current`
__Special Needs Activity Coordinator__

- Planned and organized activities for individuals with special needs, including arts and crafts, recreational games, and social events.
- Collaborated with other volunteers.
- Led and facilitated activities.

`2019-2021`
__Full Time Representive, The Church of Jesus Christ of Latter-day Saints__

- Adapted to different cultures, learned interpersonal skills, became fluent in Spanish.
- Planned lessons, taught lessons in meetings with volunteers.
- Connected with hundreds of different people.

<!-- ### Footer

Last updated: May 2013 -->